<?php

namespace fucodo\contact\securitycenter\Domain\Repository;

/*
 * This file is part of the KayStrobach.Contact.SecurityCenter package.
 */

use fucodo\contact\securitycenter\Domain\Model\ActivityLogEntry;
use KayStrobach\VisualSearch\Domain\Repository\SearchableRepository;
use Neos\Cache\Frontend\FrontendInterface;
use Neos\Cache\Frontend\VariableFrontend;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy;
use Neos\Flow\Persistence\QueryInterface;
use Neos\Flow\Persistence\QueryResultInterface;
use Neos\Flow\Security\Account;
use Neos\Flow\Security\Context;

#[Flow\Scope("singleton")]
class ActivityLogEntryRepository extends SearchableRepository
{
    /**
     * The security context of the current request
     */
    #[Flow\Inject]
    protected Context $securityContext;

    protected $defaultOrderings = [
        'createdAt' => QueryInterface::ORDER_DESCENDING
    ];

    #[Flow\InjectConfiguration(path: "cleanup.fallback")]
    protected ?array $fallbackConfig = null;

    protected null|FrontendInterface|DependencyProxy $cleanupCache = null;

    protected const CLEANUP_CACHE_KEY = 'lastCleanupRunAt';

    public function findByCurrentlyLoggedInAccount(): ?QueryResultInterface
    {
        $accountIdentifier = $this->securityContext?->getAccount()?->getAccountIdentifier();
        if ($accountIdentifier === null) {
            return null;
        }
        return $this->findByUser($accountIdentifier);
    }

    public function findByUser(string $accountIdentifier): QueryResultInterface
    {
        $q = $this->createQuery();
        $q->matching(
            $q->equals('userIdentity', $accountIdentifier)
        );
        return $q->execute();
    }

    public function findByNamedQueryAndAccount($name): ?QueryResultInterface
    {
        $q = parent::findByNamedQuery($name)->getQuery(); // TODO: Change the autogenerated stub
        $accountIdentifier = $this->securityContext?->getAccount()?->getAccountIdentifier();
        if ($accountIdentifier === null) {
            return null;
        }
        $q->matching(
            $q->logicalAnd(
                [
                    $q->getConstraint(),
                    $q->equals(
                        'userIdentity',
                        $accountIdentifier
                    )
                ]
            )
        );
        return $q->execute();
    }

    public function create(string $severity, string $title, string $code = '', string $message = '', bool $userApproval = false, bool $adminApproval = false, $accountIdentifier = null): ActivityLogEntry
    {
        $identity = $accountIdentifier;

        if (($identity === null) && ($this->securityContext->canBeInitialized())) {
            if ($this->securityContext->getAccount() instanceof Account) {
                $identity = $this->securityContext->getAccount()->getAccountIdentifier();
            }
        }

        if ($identity === null) {
            $identity = 'anonymous';
        }

        $log = new ActivityLogEntry();
        $log->setSeverity($severity);
        $log->setTitle($title);
        $log->setCode($code);
        $log->setMessage($message);
        $log->getAdminApproval()->setNeeded($adminApproval);
        $log->getUserApproval()->setNeeded($userApproval);
        $log->setSeverity(ActivityLogEntry::SEVERITY_NOTICE);
        $log->setUserIdentity($identity);

        $this->add($log);

        return $log;
    }

    public function createWarning(string $title, string $code = '', string $message = '', bool $userApproval = false, bool $adminApproval = false): ActivityLogEntry
    {
        return $this->create(ActivityLogEntry::SEVERITY_WARNING, $title, $code, $message, $userApproval, $adminApproval);
    }

    public function createError(string $title, string $code = '', string $message = '', bool $userApproval = false, bool $adminApproval = false): ActivityLogEntry
    {
        return $this->create(ActivityLogEntry::SEVERITY_ERROR, $title, $code, $message, $userApproval, $adminApproval);
    }

    public function createNotice(string $title, string $code = '', string $message = '', bool $userApproval = false, bool $adminApproval = false): ActivityLogEntry
    {
        return $this->create(ActivityLogEntry::SEVERITY_NOTICE, $title, $code, $message, $userApproval, $adminApproval);
    }

    public function createOk(string $title, string $code = '', string $message = '', bool $userApproval = false, bool $adminApproval = false): ActivityLogEntry
    {
        return $this->create(ActivityLogEntry::SEVERITY_OK, $title, $code, $message, $userApproval, $adminApproval);
    }

    public function add($object): void
    {
        if (!$object instanceof ActivityLogEntry) {
            throw new \InvalidArgumentException('Only ActivityLogEntry objects can be added to the repository', 1514392222);
        }

        $this->entityManager->getConnection()->insert(
            $this->entityManager->getClassMetadata(ActivityLogEntry::class)->getTableName(),
            $object->jsonSerialize()
        );

        $this->maybeRunFallbackCleanup();
    }

    public function update($object): void
    {
        $this->persistenceManager->allowObject($object);
        parent::update($object);
        $this->persistenceManager->persistAllowedObjects();
        $this->maybeRunFallbackCleanup();
    }

    protected function maybeRunFallbackCleanup(): void
    {
        if (($this->fallbackConfig['enabled'] ?? true) === false) {
            return;
        }
        if (random_int(1, max(1, (int)($this->fallbackConfig['checkProbability'] ?? 500))) !== 1) {
            return;
        }

        $lastRunAt = $this->cleanupCache->get(self::CLEANUP_CACHE_KEY);
        $maxAge = (int)($this->fallbackConfig['maxAgeInSeconds'] ?? 7200);

        if ($lastRunAt !== false && (time() - (int)$lastRunAt) < $maxAge) {
            return;
        }

        // mark as run immediately so concurrent requests in the same window don't pile on
        $this->cleanupCache->set(self::CLEANUP_CACHE_KEY, time());

        $this->deleteExpiredEntriesBatch((int)($this->fallbackConfig['batchSize'] ?? 100));
    }

    public function deleteExpiredEntriesBatch(int $limit = 1000): int
    {
        $tableName = $this->entityManager->getClassMetadata(ActivityLogEntry::class)->getTableName();
        return (int)$this->entityManager->getConnection()->executeStatement(
            'DELETE FROM ' . $tableName . ' WHERE expiresAt < :now LIMIT :limit',
            [
                'now' => (new \DateTimeImmutable())->format('Y-m-d H:i:s'), 'limit' => $limit
            ],
            [
                'limit' => \PDO::PARAM_INT
            ]
        );
    }
}
